# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  npm_config_cache: $(Pipeline.Workspace)/.npm

steps:
- checkout: self
  persistCredentials: true
- task: NodeTool@0
  inputs:
    versionSpec: '12.x'
  displayName: 'Install Node.js'
- task: CacheBeta@0
  inputs:
    key: $(Build.SourcesDirectory)/package-lock.json
    path: $(npm_config_cache)
  displayName: Cache npm
- script: |
    npm ci
    npm run build
- script: |
    npm run deploy -- -r https://$(DEPLOY_ACCESS_TOKEN)@github.com/WalletWasabi/WasabiDoc.git -u "Azure Pipeline <azure-pipeline@wasabiwallet.io>"
  displayName: 'Build and deploy'
  condition: |
    and(not(eq(variables['Build.Reason'], 'PullRequest')),
        eq(variables['Build.SourceBranch'], 'refs/heads/master'))
